// Plays a simulated game: several seats, each a real OpenCode session, all
// playing one generated world.
//
// Nothing here launches Civilization V. The material world is generated by the
// seed and advanced by the seats' own choices, so the diplomacy is causal: a
// seat only ever reads a situation that the table actually produced. A scenario
// can also inject a circumstance on a chosen turn, which is how a run studies
// how the seats react to a betrayal or a build-up rather than only how they
// play an undisturbed game.

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { SeatRuntime } from "../seat/runtime.js";
import { OpenCodeServer } from "../session/opencode-server.js";
import { SessionClient } from "../session/session-client.js";
import type { SeatModel } from "../session/types.js";
import { TraceStore } from "../trace/store.js";
import { logger } from "../utils/logger.js";
import { createSimState } from "../world/simulated/engine.js";
import { SimulatedWorld } from "../world/simulated/simulated-world.js";
import type { ScenarioShock } from "../world/simulated/scenario.js";
import type { SimConfig } from "../world/simulated/types.js";
import { writeSeatConfig } from "./seat-config.js";
import { writeTurnState } from "./turn-state.js";

// Everything a simulated run needs.
export interface SimulationOptions {
  // Where the run writes its files.
  runDirectory: string;
  // A short name for the run, used in the record and the logs.
  runId: string;
  // The seats to play, in turn order.
  seats: string[];
  // The turn to start at.
  fromTurn: number;
  // The turn to stop at, inclusive.
  toTurn: number;
  // The seed the world is generated from.
  seed: number;
  // The model every seat runs on unless it is overridden.
  model: SeatModel;
  // Per-seat model overrides, keyed by seat name.
  modelOverrides?: Record<string, SeatModel>;
  // The built tool server entry point the seats are given.
  serverEntry: string;
  // The port a seat's OpenCode server starts from. Each seat takes the next one.
  portBase: number;
  // Circumstances to inject on chosen turns.
  shocks?: ScenarioShock[];
  // The rates the world advances at.
  config?: SimConfig;
}

// What a finished run reports.
export interface SimulationResult {
  // The run identifier.
  runId: string;
  // Turns actually played, across every seat.
  turnsPlayed: number;
  // Turns a seat failed to finish.
  failures: number;
  // Information the seats asked for and did not get, counted by subject.
  gaps: Record<string, number>;
  // How many social operations the seats sent.
  socialOperations: number;
  // Circumstances the scenario injected, one line each.
  injected: string[];
}

// Play the seats through a generated game.
export async function simulate(options: SimulationOptions): Promise<SimulationResult> {
  if (options.seats.length === 0) throw new Error("A simulated run needs at least one seat");
  const socialDirectory = path.join(options.runDirectory, "social");
  const traceDirectory = path.join(options.runDirectory, "trace");
  const stateDirectory = path.join(options.runDirectory, "state");
  const worldStateFile = path.join(stateDirectory, "world.json");
  await mkdir(socialDirectory, { recursive: true });
  const store = new TraceStore(traceDirectory, options.runId);

  const world = new SimulatedWorld({
    state: createSimState({
      seats: options.seats,
      seed: options.seed,
      game: options.runId,
      startTurn: options.fromTurn
    }),
    socialDirectory,
    config: options.config,
    shocks: options.shocks ?? []
  });

  // One OpenCode server per seat, because each seat needs its own tool server
  // and its own working directory. A shared server would let two seats read
  // each other's configuration.
  const servers: OpenCodeServer[] = [];
  const clients = new Map<string, SessionClient>();
  const injected: string[] = [];
  try {
    for (let index = 0; index < options.seats.length; index += 1) {
      const seat = options.seats[index];
      const seatDirectory = path.join(options.runDirectory, "seats", seat);
      const playerID = world.seats().find((entry) => entry.seat === seat)?.playerID ?? null;
      await writeSeatConfig({
        seat,
        playerID,
        model: options.modelOverrides?.[seat] ?? options.model,
        seatDirectory,
        corpusDirectory: "",
        worldStateFile,
        socialDirectory,
        serverEntry: options.serverEntry
      });
      const server = new OpenCodeServer(seatDirectory);
      await server.start({ port: options.portBase + index });
      servers.push(server);
      const client = new SessionClient(server.address(), options.modelOverrides?.[seat] ?? options.model);
      await client.openSeat(seat, "seat " + seat);
      clients.set(seat, client);
      logger.info("Seat " + seat + " is ready on port " + (options.portBase + index));
    }

    const runtimes = new Map<string, SeatRuntime>();
    for (const seat of options.seats) {
      runtimes.set(
        seat,
        new SeatRuntime({
          client: clients.get(seat) as SessionClient,
          world,
          socialDirectory,
          store,
          toolServing: "observe",
          // The tool server runs in its own process, so the world it reads is
          // whatever the snapshot holds. Publishing it here is what keeps the
          // seat's reads and the harness's world in step.
          onTurnPrepared: async () => {
            await world.writeSnapshot(worldStateFile);
          }
        })
      );
    }

    let turnsPlayed = 0;
    let failures = 0;
    const gaps: Record<string, number> = {};
    for (let turn = options.fromTurn; turn <= options.toTurn; turn += 1) {
      for (const seat of options.seats) {
        const seatDirectory = path.join(options.runDirectory, "seats", seat);
        await writeTurnState(seatDirectory, { turn, seat });
        const runtime = runtimes.get(seat) as SeatRuntime;
        const record = await runtime.playTurn(seat, turn);
        turnsPlayed += 1;
        if (record.outcome === "failed" || record.outcome === "unfinished") failures += 1;
        for (const subject of extractGaps(record.applied ?? "")) {
          gaps[subject] = (gaps[subject] ?? 0) + 1;
        }
        logger.info(
          "turn " +
            turn +
            " " +
            seat +
            " " +
            record.outcome +
            " (cache read " +
            record.usage.cacheRead +
            ", in " +
            record.usage.input +
            ", out " +
            record.usage.output +
            ", reasoning " +
            record.usage.reasoning +
            ")"
        );
      }
      // Anything the scenario scheduled for the turn just played is recorded
      // here, so a run's report says what it did to its seats.
      for (const shock of options.shocks ?? []) {
        if (shock.turn === turn) {
          injected.push("turn " + turn + ": " + shock.kind + " on " + shock.seat + (shock.target ? " against " + shock.target : ""));
        }
      }
    }

    const summary = await store.summary();
    const socialOperations = await countSocialOperations(socialDirectory);
    await world.writeSnapshot(worldStateFile);
    await writeFile(
      path.join(options.runDirectory, "summary.json"),
      JSON.stringify({ ...summary, failures, gaps, socialOperations, injected }, null, 2),
      "utf8"
    );
    return { runId: options.runId, turnsPlayed, failures, gaps, socialOperations, injected };
  } finally {
    for (const server of servers) {
      await server.stop().catch((error) => logger.warn("Could not stop a seat server: " + String(error)));
    }
  }
}

// Count the social operations a run produced, which is the first measure of how
// much diplomacy actually happened.
async function countSocialOperations(socialDirectory: string): Promise<number> {
  try {
    const { readFile } = await import("node:fs/promises");
    const text = await readFile(path.join(socialDirectory, "social.jsonl"), "utf8");
    return text.split("\n").filter((line) => line.trim().length > 0).length;
  } catch {
    return 0;
  }
}

// Pull the subjects a seat asked for and did not get out of a record's applied
// line, so a run can report what the observation is missing.
function extractGaps(applied: string): string[] {
  const marker = "information gaps: ";
  const at = applied.indexOf(marker);
  if (at === -1) return [];
  return applied
    .slice(at + marker.length)
    .split(", ")
    .map((entry) => entry.trim())
    .filter((entry) => entry.length > 0);
}

// Read command line options and play a run. This is the entry point used from
// the console, so it says plainly what it did.
async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const value = (name: string, fallback?: string): string | undefined => {
    const at = args.indexOf("--" + name);
    return at === -1 ? fallback : args[at + 1];
  };
  const repositoryRoot = path.resolve(value("root", ".") as string);
  const runId = value("run-id", "sim-" + new Date().toISOString().replace(/[:.]/g, "-")) as string;
  const runDirectory = path.resolve(value("run-dir", path.join(repositoryRoot, "opencode-harness/runs", runId)) as string);
  const seats = ((value("seats", "korea,austria,siam,iroquois") as string) || "")
    .split(",")
    .map((seat) => seat.trim())
    .filter(Boolean);
  const fromTurn = Number(value("from", "1"));
  const toTurn = Number(value("to", "3"));
  const portBase = Number(value("port-base", "4300"));
  const seed = Number(value("seed", "11"));
  const modelSetting = (value("model", "opencode-go/deepseek-v4.1-flash") as string).split("/");
  const serverEntry = path.resolve(
    value("server", path.join(repositoryRoot, "opencode-harness/dist/mcp/seat-mcp.js")) as string
  );
  const scenarioFile = value("scenario", undefined) as string | undefined;
  const shocks = scenarioFile ? await readScenario(repositoryRoot, scenarioFile) : [];

  const result = await simulate({
    runDirectory,
    runId,
    seats,
    fromTurn,
    toTurn,
    seed,
    model: { providerID: modelSetting[0], modelID: modelSetting.slice(1).join("/") },
    serverEntry,
    portBase,
    shocks
  });
  logger.info(
    "Run " +
      result.runId +
      " finished: " +
      result.turnsPlayed +
      " turn(s), " +
      result.failures +
      " unfinished or failed, " +
      result.socialOperations +
      " social operation(s), gaps " +
      JSON.stringify(result.gaps)
  );
  process.exit(0);
}

// Read a scenario file, which lists the circumstances a run should inject.
async function readScenario(repositoryRoot: string, file: string): Promise<ScenarioShock[]> {
  const { readFile } = await import("node:fs/promises");
  const resolved = path.isAbsolute(file) ? file : path.join(repositoryRoot, file);
  const parsed: unknown = JSON.parse(await readFile(resolved, "utf8"));
  if (!Array.isArray(parsed)) throw new Error("A scenario file must hold an array of shocks");
  return parsed as ScenarioShock[];
}

// Only run when invoked as a program, so importing this file in a test does not
// start a game.
if (process.argv[1] && process.argv[1].endsWith("simulate.js")) {
  await main();
}
