import Database from 'better-sqlite3';

export const currentSocialSchemaVersion = 12;
type Sqlite = InstanceType<typeof Database>;

/** Apply ordered social schema migrations without rewriting current databases. */
export function migrateSocialSchema(sqlite: Sqlite): void {
  const version = Number(sqlite.pragma('user_version', { simple: true }));
  if (version > currentSocialSchemaVersion) throw new Error(`Unsupported social schema version ${version}`);
  for (let next = version + 1; next <= currentSocialSchemaVersion; next += 1) sqlite.transaction(() => { applyMigration(sqlite, next); sqlite.pragma(`user_version = ${next}`); })();
}

/** Apply one migration boundary. */
function applyMigration(sqlite: Sqlite, version: number): void {
  if (version === 1) sqlite.exec(`CREATE TABLE IF NOT EXISTS socialSessions (id TEXT PRIMARY KEY, humanActorId TEXT NOT NULL, createdAt TEXT NOT NULL); CREATE TABLE IF NOT EXISTS socialActors (id TEXT PRIMARY KEY, sessionId TEXT NOT NULL, ordinal INTEGER NOT NULL, control TEXT NOT NULL, displayName TEXT NOT NULL, modelRef TEXT, profile TEXT, createdAt TEXT NOT NULL, status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS socialChannels (id TEXT PRIMARY KEY, sessionId TEXT NOT NULL, kind TEXT NOT NULL, title TEXT NOT NULL, createdByActorId TEXT NOT NULL, canonicalKey TEXT, createdAt TEXT NOT NULL, archived INTEGER NOT NULL DEFAULT 0, UNIQUE(sessionId, canonicalKey)); CREATE TABLE IF NOT EXISTS socialMemberships (id TEXT PRIMARY KEY, channelId TEXT NOT NULL, actorId TEXT NOT NULL, status TEXT NOT NULL, invitedByActorId TEXT, visibleAfterMessageId INTEGER NOT NULL, leftAfterMessageId INTEGER, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL); CREATE TABLE IF NOT EXISTS socialMessages (id INTEGER PRIMARY KEY AUTOINCREMENT, channelId TEXT NOT NULL, speakerActorId TEXT NOT NULL, content TEXT NOT NULL, replyToMessageId INTEGER, createdAt TEXT NOT NULL, intentionId TEXT, idempotencyKey TEXT UNIQUE); CREATE TABLE IF NOT EXISTS socialMemories (actorId TEXT PRIMARY KEY, revision INTEGER NOT NULL, content TEXT NOT NULL, updatedAt TEXT NOT NULL, sourceRunId TEXT); CREATE TABLE IF NOT EXISTS socialIntentions (id TEXT PRIMARY KEY, actorId TEXT NOT NULL, kind TEXT NOT NULL, channelId TEXT, sourceMessageId INTEGER, priority INTEGER NOT NULL, state TEXT NOT NULL, notBefore TEXT NOT NULL, payload TEXT, dedupeKey TEXT UNIQUE, attemptCount INTEGER NOT NULL DEFAULT 0, lastError TEXT, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL); CREATE INDEX IF NOT EXISTS socialMessagesChannelIdIndex ON socialMessages(channelId, id); CREATE INDEX IF NOT EXISTS socialMembershipsActorIndex ON socialMemberships(actorId, channelId);`);
  if (version === 2) { addColumn(sqlite, 'socialSessions', 'title', "TEXT NOT NULL DEFAULT 'Untitled sandbox'"); addColumn(sqlite, 'socialSessions', 'archived', 'INTEGER NOT NULL DEFAULT 0'); addColumn(sqlite, 'socialSessions', 'updatedAt', "TEXT NOT NULL DEFAULT ''"); sqlite.exec("UPDATE socialSessions SET updatedAt = createdAt WHERE updatedAt = ''"); }
  if (version === 3) { addColumn(sqlite, 'socialIntentions', 'claimedAt', 'TEXT'); addColumn(sqlite, 'socialIntentions', 'result', 'TEXT'); sqlite.exec('CREATE INDEX IF NOT EXISTS socialIntentionsClaimIndex ON socialIntentions(state, notBefore, priority, createdAt);'); sqlite.exec("UPDATE socialActors SET modelRef = 'openrouter/' || modelRef WHERE modelRef IS NOT NULL AND modelRef NOT LIKE 'openrouter/%' AND (modelRef LIKE 'inclusionai/%' OR modelRef LIKE 'dots-studio/%' OR modelRef LIKE 'nvidia/%' OR modelRef LIKE 'liquid/%' OR modelRef LIKE 'poolside/%' OR modelRef LIKE 'thinkingmachines/%' OR modelRef LIKE 'z-ai/%' OR modelRef LIKE 'minimax/%')"); }
  if (version === 4) { addColumn(sqlite, 'socialIntentions', 'cascadeId', 'TEXT'); addColumn(sqlite, 'socialIntentions', 'operationClass', "TEXT NOT NULL DEFAULT 'ai-cascade'"); addColumn(sqlite, 'socialIntentions', 'completedAt', 'TEXT'); sqlite.exec('CREATE TABLE IF NOT EXISTS socialCascades (id TEXT PRIMARY KEY, sessionId TEXT NOT NULL, rootKind TEXT NOT NULL, rootMessageId INTEGER, state TEXT NOT NULL, modelRuns INTEGER NOT NULL DEFAULT 0, committedModelMessages INTEGER NOT NULL DEFAULT 0, maxModelRuns INTEGER NOT NULL, maxCommittedModelMessages INTEGER NOT NULL, maxRepliesPerActor INTEGER NOT NULL, maxWallClockMs INTEGER NOT NULL, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL); CREATE INDEX IF NOT EXISTS socialIntentionsCascadeIndex ON socialIntentions(cascadeId, state, createdAt); CREATE INDEX IF NOT EXISTS socialIntentionsActorCascadeIndex ON socialIntentions(actorId, cascadeId, result);'); }
  if (version === 5) { const duplicate = sqlite.prepare("SELECT channelId, actorId FROM socialMemberships WHERE status IN ('invited','active') GROUP BY channelId, actorId HAVING COUNT(*) > 1").get() as { channelId: string; actorId: string } | undefined; if (duplicate) throw new Error(`Cannot migrate social memberships: duplicate current membership for channel ${duplicate.channelId} and actor ${duplicate.actorId}`); sqlite.exec("CREATE UNIQUE INDEX IF NOT EXISTS socialMembershipsCurrentUnique ON socialMemberships(channelId, actorId) WHERE status IN ('invited','active');"); }
  if (version === 6) sqlite.exec('CREATE INDEX IF NOT EXISTS socialIntentionsWakeIndex ON socialIntentions(state, notBefore, priority, createdAt); CREATE INDEX IF NOT EXISTS socialCascadesStateIndex ON socialCascades(sessionId, state, updatedAt);');
  if (version === 7) sqlite.exec(`CREATE TABLE IF NOT EXISTS socialEnvironmentBindings (sessionId TEXT NOT NULL, environmentType TEXT NOT NULL, gameId TEXT NOT NULL, actorId TEXT NOT NULL, playerId INTEGER NOT NULL, controlMode TEXT NOT NULL, civilizationType TEXT, leaderType TEXT, active INTEGER NOT NULL DEFAULT 1, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL, PRIMARY KEY(sessionId, actorId), UNIQUE(sessionId, environmentType, gameId, playerId)); CREATE INDEX IF NOT EXISTS socialEnvironmentBindingsGameIndex ON socialEnvironmentBindings(sessionId, environmentType, gameId); CREATE TABLE IF NOT EXISTS socialEnvironmentEvents (id INTEGER PRIMARY KEY AUTOINCREMENT, sessionId TEXT NOT NULL, environmentType TEXT NOT NULL, gameId TEXT NOT NULL, sourceKey TEXT NOT NULL UNIQUE, turn INTEGER, eventType TEXT NOT NULL, sourcePlayerId INTEGER, targetPlayerId INTEGER, normalizedPayloadJson TEXT NOT NULL, occurredAt TEXT, createdAt TEXT NOT NULL); CREATE INDEX IF NOT EXISTS socialEnvironmentEventsSessionIndex ON socialEnvironmentEvents(sessionId, environmentType, gameId, id);`);
  if (version === 8) sqlite.exec(`CREATE TABLE IF NOT EXISTS socialCivActionAttempts (operationId TEXT PRIMARY KEY, sessionId TEXT NOT NULL, actorId TEXT NOT NULL, gameId TEXT NOT NULL, playerId INTEGER NOT NULL, sourceTurn INTEGER NOT NULL, actionType TEXT NOT NULL, category TEXT NOT NULL, normalizedArgumentsJson TEXT NOT NULL, state TEXT NOT NULL, requestedAt TEXT NOT NULL, executingAt TEXT, completedAt TEXT, resultSummary TEXT, failureClass TEXT, readbackSummary TEXT); CREATE INDEX IF NOT EXISTS socialCivActionAttemptsActorIndex ON socialCivActionAttempts(sessionId, actorId, requestedAt);`);
  if (version === 9) sqlite.exec('CREATE INDEX IF NOT EXISTS socialEnvironmentEventsSourceIndex ON socialEnvironmentEvents(sessionId, sourceKey);');
  if (version === 10) sqlite.exec('CREATE TABLE IF NOT EXISTS socialDecisionDiagnostics (id TEXT PRIMARY KEY, intentionId TEXT NOT NULL, actorId TEXT NOT NULL, actorDisplayName TEXT NOT NULL, modelRef TEXT, executionScope TEXT NOT NULL, selectedKind TEXT, routingRefsJson TEXT, validationOutcome TEXT NOT NULL, applicationOutcome TEXT, error TEXT, latencyMs INTEGER, retryCount INTEGER NOT NULL DEFAULT 0, createdAt TEXT NOT NULL); CREATE INDEX IF NOT EXISTS socialDecisionDiagnosticsIntentionIndex ON socialDecisionDiagnostics(intentionId, createdAt); CREATE INDEX IF NOT EXISTS socialDecisionDiagnosticsActorIndex ON socialDecisionDiagnostics(actorId, createdAt);');
  if (version === 11) { addColumn(sqlite, 'socialSessions', 'pacingProfile', "TEXT NOT NULL DEFAULT 'balanced'"); addColumn(sqlite, 'socialDecisionDiagnostics', 'cascadeId', 'TEXT'); addColumn(sqlite, 'socialDecisionDiagnostics', 'providerLatencyMs', 'INTEGER'); addColumn(sqlite, 'socialDecisionDiagnostics', 'queueWaitMs', 'INTEGER'); addColumn(sqlite, 'socialDecisionDiagnostics', 'durationMs', 'INTEGER'); addColumn(sqlite, 'socialDecisionDiagnostics', 'inputTokens', 'INTEGER'); addColumn(sqlite, 'socialDecisionDiagnostics', 'outputTokens', 'INTEGER'); addColumn(sqlite, 'socialDecisionDiagnostics', 'totalTokens', 'INTEGER'); addColumn(sqlite, 'socialDecisionDiagnostics', 'cachedTokens', 'INTEGER'); addColumn(sqlite, 'socialDecisionDiagnostics', 'reasoningTokens', 'INTEGER'); addColumn(sqlite, 'socialDecisionDiagnostics', 'cost', 'REAL'); }
  if (version === 12) addColumn(sqlite, 'socialIntentions', 'modelStartedAt', 'TEXT');
}

/** Add a column only when upgrading a legacy table that lacks it. */
function addColumn(sqlite: Sqlite, table: string, column: string, definition: string): void { const columns = sqlite.prepare(`PRAGMA table_info(${table})`).all() as Array<{ name: string }>; if (!columns.some((candidate) => candidate.name === column)) sqlite.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`); }
