import { Router, type Request, type Response } from 'express';
import path from 'node:path';
import { SocialRuntime, type SocialRuntimeConfig } from '../../social/runtime/social-runtime.js';
import type { SocialActorDefinition, SocialPacingProfile } from '../../social/types.js';
import { SocialEventProjector } from '../../social/events/social-event-projector.js';

const router = Router();
export const socialRuntime = new SocialRuntime();
const socialDataDirectory = path.join(process.cwd(), 'social-data');

/** Return a request body as a record when it is a JSON object. */
function bodyRecord(body: unknown): Record<string, unknown> | undefined { return body !== null && typeof body === 'object' && !Array.isArray(body) ? body as Record<string, unknown> : undefined; }
/** Return a boolean query flag. */
function queryFlag(value: unknown): boolean { return value === true || value === 'true' || value === '1'; }
/** Return a safe route error message. */
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : 'Unexpected social runtime error'; }
/** Accept only the centralized pacing profiles exposed by the sandbox. */
function pacingProfile(value: unknown): SocialPacingProfile { return value === 'quiet' || value === 'lively' ? value : 'balanced'; }
/** Validate the actor list accepted by the standalone social session endpoint. */
function actorDefinitions(value: unknown): SocialActorDefinition[] | undefined { if (!Array.isArray(value)) return undefined; if (value.length < 2 || value.length > 8) return undefined; const actors: SocialActorDefinition[] = []; for (const item of value) { const record = bodyRecord(item); if (!record || typeof record.id !== 'string' || typeof record.ordinal !== 'number' || (record.control !== 'human' && record.control !== 'model') || typeof record.displayName !== 'string') return undefined; actors.push({ id: record.id, ordinal: record.ordinal, control: record.control, displayName: record.displayName, ...(typeof record.modelRef === 'string' ? { modelRef: record.modelRef } : {}), ...(typeof record.profile === 'string' ? { profile: record.profile } : {}) }); } return actors; }

/** Start a standalone social session without Civilization V. */
router.post('/session', async (req: Request, res: Response) => { try { const body = bodyRecord(req.body); const actors = actorDefinitions(body?.actors); if (!actors) { res.status(400).json({ error: 'actors must contain 2 to 8 valid actor definitions' }); return; } const runtimeConfig: SocialRuntimeConfig = { actors, dataDirectory: path.join(process.cwd(), 'social-data'), pacingProfile: pacingProfile(body?.pacingProfile), ...(typeof body?.sessionId === 'string' ? { sessionId: body.sessionId } : {}), ...(typeof body?.humanActorId === 'string' ? { humanActorId: body.humanActorId } : {}), ...(typeof body?.title === 'string' ? { title: body.title } : {}) }; await socialRuntime.start(runtimeConfig); res.status(201).json({ sessionId: socialRuntime.getSessionId(), humanActorId: socialRuntime.getHumanActorId(), pacingProfile: socialRuntime.getPacingProfile(), actors: await socialRuntime.listActors() }); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** Stop the standalone social session. */
router.post('/session/stop', async (_req: Request, res: Response) => { try { await socialRuntime.stop(); res.json({ success: true }); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** List persisted social sessions available after a server restart. */
router.get('/sessions', async (_req: Request, res: Response) => { try { res.json({ sessions: await socialRuntime.listStoredSessions(socialDataDirectory) }); } catch (error) { res.status(500).json({ error: errorMessage(error) }); } });
/** Update a saved sandbox title or archive state. */
router.patch('/sessions/:sessionId', async (req: Request<{ sessionId: string }>, res: Response) => { const body = bodyRecord(req.body); const values = { ...(typeof body?.title === 'string' && body.title.trim() ? { title: body.title.trim() } : {}), ...(typeof body?.archived === 'boolean' ? { archived: body.archived } : {}) }; if (!Object.keys(values).length) { res.status(400).json({ error: 'title or archived is required' }); return; } try { res.json(await socialRuntime.updateStoredSession(req.params.sessionId, socialDataDirectory, values)); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** Permanently delete a stopped sandbox. */
router.delete('/sessions/:sessionId', async (req: Request<{ sessionId: string }>, res: Response) => { try { await socialRuntime.deleteStoredSession(req.params.sessionId, socialDataDirectory); res.json({ success: true }); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** Resume one persisted social session without changing its durable state. */
router.post('/session/resume', async (req: Request, res: Response) => { const body = bodyRecord(req.body); if (typeof body?.sessionId !== 'string') { res.status(400).json({ error: 'sessionId is required' }); return; } try { await socialRuntime.resume(body.sessionId, socialDataDirectory); res.json({ sessionId: socialRuntime.getSessionId(), humanActorId: socialRuntime.getHumanActorId(), pacingProfile: socialRuntime.getPacingProfile(), actors: await socialRuntime.listActors() }); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** Return social session status and actor definitions. */
router.get('/session', async (_req: Request, res: Response) => { if (!socialRuntime.isRunning()) { res.status(404).json({ error: 'No social session is active' }); return; } res.json({ sessionId: socialRuntime.getSessionId(), humanActorId: socialRuntime.getHumanActorId(), pacingProfile: socialRuntime.getPacingProfile(), actors: await socialRuntime.listActors(), inspectionAvailable: socialRuntime.inspectionAvailable(), scheduler: { running: true } }); });
/** Return sanitized model-decision diagnostics only when developer inspection is enabled. */
router.get('/diagnostics', async (req: Request, res: Response) => { if (!socialRuntime.isRunning() || !socialRuntime.inspectionAvailable()) { res.status(404).json({ error: 'Developer diagnostics are unavailable' }); return; } const limit = typeof req.query.limit === 'string' && /^\d+$/.test(req.query.limit) ? Math.min(Number(req.query.limit), 10_000) : 100; try { res.json({ diagnostics: await socialRuntime.listDecisionDiagnostics(limit), cascades: await socialRuntime.listCascades(50) }); } catch (error) { res.status(500).json({ error: errorMessage(error) }); } });
/** Wait for a durable cascade result instead of inferring completion from telemetry timing. */
router.get('/cascades/:cascadeId/wait', async (req: Request<{ cascadeId: string }>, res: Response) => { if (!socialRuntime.isRunning() || !socialRuntime.inspectionAvailable()) { res.status(404).json({ error: 'Developer diagnostics are unavailable' }); return; } const timeoutValue = typeof req.query.timeoutMs === 'string' && /^\d+$/.test(req.query.timeoutMs) ? Number(req.query.timeoutMs) : 90_000; try { res.json(await socialRuntime.waitForCascadeSettled(req.params.cascadeId, Math.min(timeoutValue, 300_000))); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** Wait for the active scheduler drain when a benchmark is exercising non-cascade intentions. */
router.get('/idle/wait', async (req: Request, res: Response) => { if (!socialRuntime.isRunning() || !socialRuntime.inspectionAvailable()) { res.status(404).json({ error: 'Developer diagnostics are unavailable' }); return; } const timeoutValue = typeof req.query.timeoutMs === 'string' && /^\d+$/.test(req.query.timeoutMs) ? Number(req.query.timeoutMs) : 90_000; try { res.json(await socialRuntime.waitForIdle(Math.min(timeoutValue, 300_000))); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** List invitations addressed to the human viewer without exposing hidden transcripts. */
router.get('/invitations', async (_req: Request, res: Response) => { try { res.json({ invitations: await socialRuntime.listPendingInvitations() }); } catch (error) { res.status(404).json({ error: errorMessage(error) }); } });
/** Change one model actor's model for future replies without interrupting the session. */
router.patch('/actors/:actorId', async (req: Request<{ actorId: string }>, res: Response) => { const body = bodyRecord(req.body); if (typeof body?.modelRef !== 'string' || !body.modelRef.includes('/')) { res.status(400).json({ error: 'modelRef must be a provider/model identifier' }); return; } try { res.json(await socialRuntime.updateActorModel(req.params.actorId, body.modelRef)); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** List channels visible to the human, optionally using read-only developer inspection. */
router.get('/channels', async (req: Request, res: Response) => { try { res.json({ channels: await socialRuntime.listChannels(queryFlag(req.query.inspect) && socialRuntime.inspectionAvailable()) }); } catch (error) { res.status(404).json({ error: errorMessage(error) }); } });
/** Read a channel with paging and authorization. */
router.get('/channels/:channelId/messages', async (req: Request<{ channelId: string }>, res: Response) => { try { const parseInteger = (value: unknown): number | undefined => { if (value === undefined) return undefined; if (typeof value !== 'string' || !/^\d+$/.test(value)) throw new Error('Pagination values must be finite integers'); const parsed = Number(value); if (!Number.isSafeInteger(parsed)) throw new Error('Pagination values must be finite integers'); return parsed; }; const limit = parseInteger(req.query.limit); const beforeId = parseInteger(req.query.beforeId); res.json(await socialRuntime.readMessages(req.params.channelId, limit, beforeId, queryFlag(req.query.inspect) && socialRuntime.inspectionAvailable())); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** Append a human-authored message with server-bound identity. */
router.post('/channels/:channelId/messages', async (req: Request<{ channelId: string }>, res: Response) => { const body = bodyRecord(req.body); if (typeof body?.content !== 'string' || body.content.trim() === '') { res.status(400).json({ error: 'content is required' }); return; } try { const message = await socialRuntime.appendHumanMessage(req.params.channelId, body.content, typeof body.replyToMessageId === 'number' ? body.replyToMessageId : undefined); res.status(201).json(message); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** Open a human DM. */
router.post('/dms/:actorId', async (req: Request<{ actorId: string }>, res: Response) => { try { const body = bodyRecord(req.body); res.status(201).json(await socialRuntime.openHumanDm(req.params.actorId, typeof body?.title === 'string' ? body.title : undefined)); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** Create a titled group owned by the human. */
router.post('/groups', async (req: Request, res: Response) => { const body = bodyRecord(req.body); if (typeof body?.title !== 'string' || body.title.trim() === '') { res.status(400).json({ error: 'title is required' }); return; } const invitees = Array.isArray(body.invitedActorIds) && body.invitedActorIds.every((id) => typeof id === 'string') ? body.invitedActorIds as string[] : []; try { res.status(201).json(await socialRuntime.createHumanGroup(body.title, invitees)); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** Invite an actor to a human-accessible group. */
router.post('/groups/:channelId/invitations', async (req: Request<{ channelId: string }>, res: Response) => { const body = bodyRecord(req.body); if (typeof body?.actorId !== 'string') { res.status(400).json({ error: 'actorId is required' }); return; } try { res.status(201).json(await socialRuntime.invite(req.params.channelId, body.actorId)); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** Resolve the human's pending invitation. */
router.post('/groups/:channelId/invitation', async (req: Request<{ channelId: string }>, res: Response) => { const body = bodyRecord(req.body); if (typeof body?.accepted !== 'boolean') { res.status(400).json({ error: 'accepted is required' }); return; } try { res.json(await socialRuntime.resolveHumanInvitation(req.params.channelId, body.accepted)); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });
/** Leave a human group. */
router.post('/groups/:channelId/leave', async (req: Request<{ channelId: string }>, res: Response) => { try { res.json(await socialRuntime.leave(req.params.channelId)); } catch (error) { res.status(400).json({ error: errorMessage(error) }); } });

/** Stream committed social events as an SSE connection. */
router.get('/events/stream', async (req: Request, res: Response) => { if (!socialRuntime.isRunning()) { res.status(404).json({ error: 'No social session is active' }); return; } const projector = new SocialEventProjector((channelId) => socialRuntime.canHumanSeeChannel(channelId), queryFlag(req.query.inspect) && socialRuntime.inspectionAvailable(), (actorId) => actorId === socialRuntime.getHumanActorId()); res.setHeader('Content-Type', 'text/event-stream'); res.setHeader('Cache-Control', 'no-cache'); res.setHeader('Connection', 'keep-alive'); res.flushHeaders(); const unsubscribe = socialRuntime.events.subscribe((event) => { void (async () => { const projected = await projector.project(event); if (!projected) return; res.write(`event: ${projected.type}\ndata: ${JSON.stringify(projected)}\n\n`); })(); }); req.on('close', unsubscribe); });

export default router;
